name: CI publish

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  validation:
    name: "Gradle Wrapper Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: gradle/actions/wrapper-validation@v6

  build:
    name: Build and publish
    needs: validation
    runs-on: ubuntu-latest
    env:
      SNAPSHOT_BUILD: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: Check out source
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21.0.2'

      - name: Choose repository
        id: remoteRepository
        run: echo location=$([ "${{ github.ref }}" = "refs/heads/master" ] && echo "${SNAPSHOT}" || echo "${STAGING}") >> $GITHUB_OUTPUT
        env:
          SNAPSHOT: https://central.sonatype.com/repository/maven-snapshots
          STAGING: https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2

      - name: Build snapshot
        run: ./gradlew publish -x test -x check -PREPOSITORY_URL=${URL}
        if: ${{ env.SNAPSHOT_BUILD == 'true' }}
        env:
          URL: ${{ steps.remoteRepository.outputs.location }}
          VERSION: ${{ github.ref_name }}
          ORG_GRADLE_PROJECT_repositoryUserName: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_repositoryPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingKeyName: ${{ secrets.SIGNING_KEYNAME }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}

      - name: Build release
        run: ./gradlew publish -x test -x check -PREPOSITORY_URL=${URL} -PREPOSITORY_POST_URL=${POST_URL} -PTAG_VERSION_PROJECT=${VERSION}
        if: ${{ env.SNAPSHOT_BUILD == 'false' }}
        env:
          URL: ${{ steps.remoteRepository.outputs.location }}
          POST_URL: https://ossrh-staging-api.central.sonatype.com/manual/upload/defaultRepository/org.jfxcore
          VERSION: ${{ github.ref_name }}
          ORG_GRADLE_PROJECT_repositoryUserName: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_repositoryPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingKeyName: ${{ secrets.SIGNING_KEYNAME }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
